# Generated by Django 5.2.7 on 2025-10-22 04:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('video', 'Video'), ('enlace', 'Enlace')], default='texto', max_length=10)),
                ('valor_texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('valor_imagen', models.ImageField(blank=True, null=True, upload_to='index/')),
                ('valor_video', models.FileField(blank=True, null=True, upload_to='index/videos/')),
                ('valor_enlace', models.URLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='myapp.seccion')),
            ],
            options={
                'verbose_name': 'Contenido del Index',
                'verbose_name_plural': 'Contenidos del Index',
                'ordering': ['seccion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAnimacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activar_animacion', models.BooleanField(default=True)),
                ('tipo_animacion', models.CharField(choices=[('fadeIn', 'Aparecer gradualmente'), ('slideInUp', 'Deslizar desde abajo'), ('slideInLeft', 'Deslizar desde izquierda'), ('slideInRight', 'Deslizar desde derecha'), ('zoomIn', 'Zoom in'), ('bounceIn', 'Rebote')], default='fadeIn', max_length=20)),
                ('duracion', models.IntegerField(default=1000, help_text='Duración en milisegundos')),
                ('delay', models.IntegerField(default=0, help_text='Retardo en milisegundos')),
                ('seccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.seccion')),
            ],
            options={
                'verbose_name': 'Configuración de Animación',
                'verbose_name_plural': 'Configuraciones de Animaciones',
            },
        ),
    ]
