# Generated by Django 3.2.25 on 2025-11-13 14:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación de Chat IA',
                'verbose_name_plural': 'Conversaciones de Chat IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Admin'), ('en_proceso', 'En Proceso'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('cliente_nombre_dato', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_email_dato', models.EmailField(blank=True, max_length=254, null=True)),
                ('cliente_telefono_dato', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_rut_dato', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_mensaje_dato', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('admin_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_cotizacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat de Cotización',
                'verbose_name_plural': 'Chats de Cotizaciones',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('cliente_rut', models.CharField(blank=True, max_length=12, verbose_name='RUT del Cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Cliente')),
                ('cliente_telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono del Cliente')),
                ('numero_cotizacion', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Cotización')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='borrador', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Internas')),
                ('notas_cliente', models.TextField(blank=True, verbose_name='Notas para el Cliente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización (Formulario)',
                'verbose_name_plural': 'Cotizaciones (Formulario)',
                'db_table': 'cotizaciones_formulario',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU Único')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de Compra')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Disponible')),
                ('stock_minimo', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo de Seguridad')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('agotado', 'Agotado')], default='activo', max_length=10)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo en Sistema')),
                ('potencia', models.CharField(blank=True, max_length=50, verbose_name='Potencia')),
                ('voltaje', models.CharField(blank=True, max_length=50, verbose_name='Voltaje')),
                ('dimensiones', models.CharField(blank=True, max_length=100, verbose_name='Dimensiones')),
                ('icono', models.CharField(default='box', max_length=50, verbose_name='Icono FontAwesome')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.categoria', verbose_name='Categoría')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=myapp.models.upload_to_producto_path, verbose_name='Archivo de Imagen')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='myapp.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'db_table': 'producto_imagenes',
                'ordering': ['-es_principal', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAdquirido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_adquisicion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Adquisición')),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('garantia_meses', models.IntegerField(default=12, verbose_name='Meses de Garantía')),
                ('estado_garantia', models.CharField(choices=[('activa', 'Garantía Activa'), ('expirada', 'Garantía Expirada'), ('usada', 'Garantía Usada')], default='activa', max_length=20)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_adquiridos', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.producto')),
            ],
            options={
                'verbose_name': 'Producto Adquirido',
                'verbose_name_plural': 'Productos Adquiridos',
                'db_table': 'productos_adquiridos',
                'ordering': ['-fecha_compra'],
                'unique_together': {('cliente', 'producto', 'fecha_compra')},
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfiles',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Movida')),
                ('cantidad_anterior', models.IntegerField(verbose_name='Stock Anterior')),
                ('cantidad_nueva', models.IntegerField(verbose_name='Stock Nuevo')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Número de Referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='myapp.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='MensajeCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_bot', models.BooleanField(default=False)),
                ('mensaje', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cotizaciones_img/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='myapp.chatcotizacion')),
            ],
            options={
                'verbose_name': 'Mensaje de Cotización',
                'verbose_name_plural': 'Mensajes de Cotizaciones',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.producto')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de Cotización',
                'db_table': 'items_cotizacion',
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255, unique=True, verbose_name='Nombre o Código del Proyecto')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio Estimada')),
                ('fecha_termino_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Término Estimada')),
                ('fecha_termino_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Término Real')),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado / Pendiente de Aprobación'), ('aprobado', 'Aprobado / Esperando Inicio'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado / Entregado'), ('garantia', 'En Garantía'), ('cancelado', 'Cancelado')], default='cotizado', max_length=20, verbose_name='Estado Actual')),
                ('observaciones', models.TextField(blank=True, verbose_name='Notas del Administrador')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Total Estimado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Asociado')),
                ('producto_adquirido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productoadquirido', verbose_name='Producto Adquirido')),
            ],
            options={
                'verbose_name': 'Instalación (Proyecto)',
                'verbose_name_plural': 'Instalaciones (Proyectos)',
                'db_table': 'instalaciones_proyectos',
                'ordering': ['estado', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_bot', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.chatconversation')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat IA',
                'verbose_name_plural': 'Mensajes de Chat IA',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chatcotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats_cotizacion', to='myapp.producto'),
        ),
    ]
