# Generated by Django 4.2.14 on 2025-11-11 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255, unique=True, verbose_name='Nombre o Código del Proyecto')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio Estimada')),
                ('fecha_termino_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Término Estimada')),
                ('fecha_termino_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Término Real')),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado / Pendiente de Aprobación'), ('aprobado', 'Aprobado / Esperando Inicio'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado / Entregado'), ('garantia', 'En Garantía'), ('cancelado', 'Cancelado')], default='cotizado', max_length=20, verbose_name='Estado Actual')),
                ('observaciones', models.TextField(blank=True, verbose_name='Notas del Administrador')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Total Estimado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Asociado')),
                ('producto_adquirido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productoadquirido', verbose_name='Producto Adquirido')),
            ],
            options={
                'verbose_name': 'Instalación (Proyecto)',
                'verbose_name_plural': 'Instalaciones (Proyectos)',
                'db_table': 'instalaciones_proyectos',
                'ordering': ['estado', '-fecha_inicio'],
            },
        ),
    ]
