# Generated by Django 5.2.7 on 2025-11-04 05:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dimensiones',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dimensiones'),
        ),
        migrations.AddField(
            model_name='producto',
            name='icono',
            field=models.CharField(default='box', max_length=50, verbose_name='Icono FontAwesome'),
        ),
        migrations.AddField(
            model_name='producto',
            name='potencia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Potencia'),
        ),
        migrations.AddField(
            model_name='producto',
            name='voltaje',
            field=models.CharField(blank=True, max_length=50, verbose_name='Voltaje'),
        ),
        migrations.CreateModel(
            name='ProductoAdquirido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_adquisicion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Adquisición')),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('garantia_meses', models.IntegerField(default=12, verbose_name='Meses de Garantía')),
                ('estado_garantia', models.CharField(choices=[('activa', 'Garantía Activa'), ('expirada', 'Garantía Expirada'), ('usada', 'Garantía Usada')], default='activa', max_length=20)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_adquiridos', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.producto')),
            ],
            options={
                'verbose_name': 'Producto Adquirido',
                'verbose_name_plural': 'Productos Adquiridos',
                'db_table': 'productos_adquiridos',
                'ordering': ['-fecha_compra'],
                'unique_together': {('cliente', 'producto', 'fecha_compra')},
            },
        ),
    ]
