# Generated by Django 5.2.7 on 2025-10-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_seccion_contenidoindex_configuracionanimacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidoindex',
            name='seccion',
        ),
        migrations.DeleteModel(
            name='ConfiguracionAnimacion',
        ),
        migrations.DeleteModel(
            name='ContenidoIndex',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
