# Generated by Django 5.2.7 on 2025-10-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_contenidoindex_seccion_and_more'),
        ('myapp', '0003_remove_contenidoindex_seccion_chatconversation_and_more'),
    ]

    operations = [
    ]
